name: Docker Badges CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'
jobs:
  update-badges:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update Badge for Docker
        run: |
            python3 .github/workflows/update_badge.py
      - name: Push to Repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update badge config automatically
