name: Docker Rebuild CI
on:
  workflow_dispatch:
    inputs:
      rebuild-options:
        description: 'rebuild options'
        required: true
        default: 'force-none'
        type: choice
        options:
        - force-none
        - force-all
        - force-gazebo
  schedule:
    - cron: '0 6 * * *'
jobs:
  rebuild-ros-base:
    strategy:
      matrix:
        include:
          - BASE_IMAGE: gezp/ubuntu-desktop:20.04
            DOCKER_TAG: galactic
          - BASE_IMAGE: gezp/ubuntu-desktop:22.04
            DOCKER_TAG: humble
          - BASE_IMAGE: gezp/ubuntu-desktop:22.04
            DOCKER_TAG: rolling
    env:
      DOCKER_TAG: ${{ matrix.DOCKER_TAG }}
    runs-on: ubuntu-latest
    steps:
      - name: Base Image Update Checker
        id: update_checker
        uses: lucacome/docker-image-update-checker@v1.2.1
        with:
          base-image: ${{ matrix.BASE_IMAGE }}
          image: gezp/ubuntu-desktop-ros:${{ matrix.DOCKER_TAG }}
      - name: Rebuild Checker
        id: rebuild_checker
        run: |
          trigger=false
          if  [ "${{steps.update_checker.outputs.needs-updating}}" == 'true' ]
          then
            trigger=true
          fi
          if  [ "${{github.event_name}}" == 'workflow_dispatch' ] && \
              [ "${{github.event.inputs.rebuild-options}}" == 'force-all' ]
          then
            trigger=true
          fi
          echo "trigger=${trigger}" >> $GITHUB_OUTPUT
      - name: Checkout
        if: steps.rebuild_checker.outputs.trigger == 'true'
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        if: steps.rebuild_checker.outputs.trigger == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Aliyun Docker Registry
        if: steps.rebuild_checker.outputs.trigger == 'true'
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hongkong.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
      - name: Build Docker Image
        if: steps.rebuild_checker.outputs.trigger == 'true'
        run: bash docker_build.sh ${{env.DOCKER_TAG}}
      - name: Push Docker Image to Docker Hub
        if: steps.rebuild_checker.outputs.trigger == 'true'
        run: |
          docker tag ubuntu-desktop-ros:${{env.DOCKER_TAG}} gezp/ubuntu-desktop-ros:${{env.DOCKER_TAG}}
          docker push gezp/ubuntu-desktop-ros:${{env.DOCKER_TAG}}
      - name: Push Docker Image to Aliyun Docker Registry (hongkong)
        if: steps.rebuild_checker.outputs.trigger == 'true'
        run: |
          docker tag ubuntu-desktop-ros:${{env.DOCKER_TAG}} registry.cn-hongkong.aliyuncs.com/gezp/ubuntu-desktop-ros:${{env.DOCKER_TAG}}
          docker push registry.cn-hongkong.aliyuncs.com/gezp/ubuntu-desktop-ros:${{env.DOCKER_TAG}}

  rebuild-gazebo:
    needs:
      - rebuild-ros-base
    strategy:
      matrix:
        include:
          - BASE_IMAGE: gezp/ubuntu-desktop-ros:humble
            DOCKER_TAG: humble-gazebo-fortress
          - BASE_IMAGE: gezp/ubuntu-desktop-ros:humble
            DOCKER_TAG: humble-gazebo-garden
    env:
      DOCKER_TAG: ${{ matrix.DOCKER_TAG }}
    runs-on: ubuntu-latest
    steps:
      - name: Base Image Update Checker
        id: update_checker
        uses: lucacome/docker-image-update-checker@v1.2.1
        with:
          base-image: ${{ matrix.BASE_IMAGE }}
          image: gezp/ubuntu-desktop-ros:${{ matrix.DOCKER_TAG }}
      - name: Rebuild Checker
        id: rebuild_checker
        run: |
          trigger=false
          if  [ "${{steps.update_checker.outputs.needs-updating}}" == 'true' ]
          then
            trigger=true
          fi
          if  [ "${{github.event_name}}" == 'workflow_dispatch' ] && \
              [ "${{github.event.inputs.rebuild-options}}" == 'force-gazebo' ]
          then
            trigger=true
          fi
          echo "trigger=${trigger}" >> $GITHUB_OUTPUT
      - name: Checkout
        if: steps.rebuild_checker.outputs.trigger == 'true'
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        if: steps.rebuild_checker.outputs.trigger == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Aliyun Docker Registry
        if: steps.rebuild_checker.outputs.trigger == 'true'
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hongkong.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
      - name: Build Docker Image
        if: steps.rebuild_checker.outputs.trigger == 'true'
        run: bash docker_build.sh ${{env.DOCKER_TAG}}
      - name: Push Docker Image to Docker Hub
        if: steps.rebuild_checker.outputs.trigger == 'true'
        run: |
          docker tag ubuntu-desktop-ros:${{env.DOCKER_TAG}} gezp/ubuntu-desktop-ros:${{env.DOCKER_TAG}}
          docker push gezp/ubuntu-desktop-ros:${{env.DOCKER_TAG}}
      - name: Push Docker Image to Aliyun Docker Registry (hongkong)
        if: steps.rebuild_checker.outputs.trigger == 'true'
        run: |
          docker tag ubuntu-desktop-ros:${{env.DOCKER_TAG}} registry.cn-hongkong.aliyuncs.com/gezp/ubuntu-desktop-ros:${{env.DOCKER_TAG}}
          docker push registry.cn-hongkong.aliyuncs.com/gezp/ubuntu-desktop-ros:${{env.DOCKER_TAG}}
